# Generated by Django 2.2 on 2020-08-08 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='comment',
            field=models.ManyToManyField(to='app01.Comment', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='name',
            field=models.CharField(default=None, max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='toresearch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app01.Research', verbose_name='Research'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='comment',
            field=models.ManyToManyField(to='app01.Comment', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='name',
            field=models.CharField(default=None, max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='typ',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app01.Research', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default=None, max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='typ',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app01.Research', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='typ',
            field=models.CharField(choices=[('p', 'Paper'), ('b', 'Blog')], default=None, max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default=None, max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='typ',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app01.Research', verbose_name='Type'),
        ),
    ]
