# Generated by Django 2.2 on 2020-08-12 10:17

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200812_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
            ],
            options={
                'verbose_name_plural': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
            ],
            options={
                'verbose_name_plural': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
            ],
            options={
                'verbose_name_plural': 'Comment',
            },
        ),
        migrations.RemoveField(
            model_name='paper',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='task',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='comment',
        ),
        migrations.AddField(
            model_name='idea',
            name='comment',
            field=mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='comment',
        ),
        migrations.AddField(
            model_name='knowledge',
            name='comment',
            field=mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Task', verbose_name='Task'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='papercomment',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Paper', verbose_name='Paper'),
        ),
    ]
