# Generated by Django 2.2 on 2020-08-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20200812_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papercomment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='projectcomment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='id',
        ),
        migrations.AddField(
            model_name='papercomment',
            name='_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
