# Generated by Django 2.2 on 2020-08-12 11:15

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20200812_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='duri',
        ),
        migrations.AddField(
            model_name='meeting',
            name='end',
            field=models.DateTimeField(default=None, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start',
            field=models.DateTimeField(default=None, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, default=None, verbose_name='Description'),
        ),
    ]
