# Generated by Django 2.2 on 2020-08-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20200812_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='file',
            field=models.FileField(blank=True, default=None, upload_to='', verbose_name='Attachment'),
        ),
    ]
