# Generated by Django 2.2 on 2020-08-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20200812_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='paper', verbose_name='Attachment'),
        ),
    ]
