# Generated by Django 2.2 on 2020-08-14 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20200812_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='paper', verbose_name='Attachment')),
            ],
            options={
                'verbose_name_plural': 'Attachment',
            },
        ),
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app01.Myfile'),
            preserve_default=False,
        ),
    ]
