# Generated by Django 2.2 on 2020-08-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20200814_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='paper', verbose_name='Attachment'),
        ),
        migrations.DeleteModel(
            name='Myfile',
        ),
    ]
