# Generated by Django 2.2 on 2020-08-14 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_auto_20200815_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='file',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app01.Myfile'),
            preserve_default=False,
        ),
    ]
