# Generated by Django 2.2 on 2020-08-14 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_paper_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='file',
            field=models.FileField(default=None, null=True, unique=True, upload_to='paper', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Myfile', to_field='file'),
        ),
    ]
