# Generated by Django 2.2 on 2020-08-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_paper__file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='_file',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='summary',
            name='_file',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
